[package]
name = "fellowship-of-the-kirat"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
bs58 = "0.5.1"
serde = "1.0.219"
solana-sdk = "2.3.1"
spl-token = "8.0.0"
tokio = { version = "1.45.1", features = ["full"] }
